default_stages: [commit, push]

fail_fast: false
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: check-yaml
      - id: check-toml
      - id: check-json
      - id: end-of-file-fixer
        exclude: LICENSE
      - id: trailing-whitespace
        exclude: ^exports/
      - id: mixed-line-ending
        args: ["--fix=lf"]
      - id: check-merge-conflict
      - id: check-ast
      - id: check-executables-have-shebangs
      - id: debug-statements
      - id: check-added-large-files
        args: ["--maxkb=500"]
      - id: check-docstring-first
      - id: detect-private-key
      - id: check-case-conflict

  # - repo: https://github.com/pre-commit/mirrors-clang-format
  #   rev: v13.0.0
  #   hooks:
  #     - id: clang-format

  - repo: https://github.com/pocc/pre-commit-hooks
    rev: master
    hooks:
      - id: clang-format
      - id: clang-tidy
      - id: oclint
      - id: uncrustify
      - id: cpplint

  - repo: https://github.com/humitos/mirrors-autoflake
    rev: v1.3
    hooks:
      - id: autoflake
        args:
          [
            "--in-place",
            "--remove-all-unused-imports",
            "--remove-unused-variable",
            "--remove-duplicate-keys",
          ]

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        additional_dependencies: [flake8-docstrings, flake8-print]
