#ifndef INCLUDE_COMMON_H
#define INCLUDE_COMMON_H

#include "ch.h"
#include "hal.h"
#include "chprintf.h"



#define PROGRAM_MASTER 0

#define PROGRAM_TEST_LEFT_ELBOW_ENCODER 1

#define PROGRAM_TEST_RIGHT_ELBOW_ENCODER 2

#define PROGRAM_TEST_ELBOW_DRIVER 3

#define PROGRAM_TEST_PID 4

#define PROGRAM_TEST_ARM_CONTROL_SYSTEM 5

#define MAIN_PROGRAM PROGRAM_TEST_LEFT_ELBOW_ENCODER



#endif
