#ifndef INCLUDE_CNFG_PERIPHERALS_H
#define INCLUDE_CNFG_PERIPHERALS_H

#include "common.h"

#define MOTOR1_PWM_HIN1 PAL_LINE(GPIOE, 11)
#define MOTOR1_PWM_LIN1 PAL_LINE(GPIOE, 10)
#define MOTOR1_PWM_HIN2 PAL_LINE(GPIOE, 13)
#define MOTOR1_PWM_LIN2 PAL_LINE(GPIOE, 12)

#define M1_CH_H1L1 1
#define M1_CH_H2L2 2

#define M1_AF_H1L1 PAL_MODE_ALTERNATE(1)
#define M1_AF_H2L2 PAL_MODE_ALTERNATE(1)

#define MOTOR2_PWM_HIN1 PAL_LINE(GPIOC, 6)
#define MOTOR2_PWM_LIN1 PAL_LINE(GPIOA, 5)
#define MOTOR2_PWM_HIN2 PAL_LINE(GPIOC, 7)
#define MOTOR2_PWM_LIN2 PAL_LINE(GPIOB, 0)

#define M2_CH_H1L1 0
#define M2_CH_H2L2 1

#define M2_AF_H1L1 PAL_MODE_ALTERNATE(3)
#define M2_AF_H2L2 PAL_MODE_ALTERNATE(3)

#define MOTOR3_PWM_HIN1 PAL_LINE(GPIOC, 8)
#define MOTOR3_PWM_LIN1 PAL_LINE(GPIOB, 1)
#define MOTOR3_PWM_HIN2 PAL_LINE(GPIOE, 9)
#define MOTOR3_PWM_LIN2 PAL_LINE(GPIOE, 8)

#define M3_CH_H1L1 2
#define M3_CH_H2L2 0

#define M3_AF_H1L1 PAL_MODE_ALTERNATE(3)
#define M3_AF_H2L2 PAL_MODE_ALTERNATE(1)

void cnfg_init(void);
#endif
