# This is a basic workflow to help you get started with Actions

name: Build firmware

# Controls when the workflow will run
on:
  push:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-firmware:
    runs-on: self-hosted 
    container: kail4ek/chibios_buildkit:20.03.4
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Build firmware
        run: make -C firmware
